sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t raven4ever/workflow_project -f Dockerfile.dev .

script:
  - docker run -e CI=true raven4ever/workflow_project npm run test -- --coverage